[package]
name = "rust-analyzer"
version = "0.1.0"
edition = "2018"
description = "Exercism's automated analyzer for the Rust track."

[dependencies]
failure = "0.1.5"
serde_json = "1.0.39"

[dependencies.serde]
version = "1.0.91"
features = ["derive"]

[dependencies.clap]
version = "2.32.0"
default-features = false

[dependencies.syn]
version = "0.15.30"
features = ["full"]
