[package]
name = "rust-analyzer"
version = "0.1.0"
edition = "2018"
description = "Exercism's automated analyzer for the Rust track."

[dependencies]
failure = "0.1.5"

[dependencies.clap]
version = "2.32.0"
default-features = false
